// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	ItemName string `json:"ItemName"`
	Status   string `json:"Status"`
}

type Todo struct {
	ID       int64  `json:"id"`
	ItemName string `json:"ItemName"`
	Status   string `json:"Status"`
}

type TodoInput struct {
	ID       int64  `json:"id"`
	ItemName string `json:"ItemName"`
	Status   string `json:"Status"`
}

type TodoInputfordelete struct {
	ID int64 `json:"id"`
}

type TodoList struct {
	Todos []*Todo `json:"todos"`
}
